### ISSUE TITLE
Allow using a custom Biome binary for development

### ISSUE THREAD

**Issue by nhedger** [biomejs/biome-zed#18]
We should provide a way of loading a custom biome binary for development purpose.

**Comment by ematipico** [comment]
Not sure it's needed, the development workflow of zed is very simple: you just load this very repository as an extension and it will work.

**Comment by luckydye** [comment]
Good idea, may be possible with the LSP settings interface.

**Comment by nhedger** [comment]
Would that be configurable in the end user's configuration?
