### ISSUE TITLE
BiomeJS extension and LSP not working properly on Zed #13492

### ISSUE THREAD

**Issue by a4arpon** [biomejs/biome-zed#24]
Issue Link (Zed Issues): https://github.com/zed-industries/zed/issues/13492#issue-2371850613

**Comment by ematipico** [comment]
You should set up `settings.json` like this:

```json
{
  "code_actions_on_format": {
    "source.fixAll.biome": true,
    "source.organizeImports.biome": true
  }
}
```

**Comment by luckydye** [comment]
See https://github.com/zed-industries/zed/issues/13492#issuecomment-2246243131 :)
