### ISSUE TITLE
Svelte Files get wrecked

### ISSUE THREAD

**Issue by ZeroPie** [biomejs/biome-zed#27]
Seems the HTML get's purged.
https://github.com/biomejs/biome-zed/assets/8741666/54bd4c63-97ab-46ab-9ee5-349e733a3e04

**Comment by ematipico** [comment]
Yikes, I thought that was fixed. This is an issue that belongs to core. Suppose you're doing formatting via stdin?

**Comment by ZeroPie** [comment]
hi emat,

i hope i am hehe,
this is how my config looks like: 
```
  "languages": {
      "TypeScript": {
        "language_servers": ["biome", "!typescript-language-server", "!eslint"]
      }
  },
  "formatter": {
    "external": {
      "command": "/Users/alej/.bun/bin/biome",
      "arguments": [
        "format",
        "--write",
        "--stdin-file-path",
        "{buffer_path}"
      ]
    }
  },
```

**Comment by ematipico** [comment]
I believe Zed is at fault here. Other clients work correctly (VScode, IntelliJ), and our tests seems to return the correct output: https://github.com/biomejs/biome/blob/main/crates/biome_cli/tests/snapshots/main_cases_handle_svelte_files/format_stdin_write_successfully.snap?plain=1
