### ISSUE TITLE
End of file error in `settings.json`

### ISSUE THREAD

**Issue by MatteoGauthier** [biomejs/biome-zed#28]
In `settings.json` file for configuring zed all the lines are erroring

![image](https://github.com/biomejs/biome-zed/assets/32040951/70c6c52d-acb2-4a85-bec6-167f711b14a7)

**Comment by ematipico** [comment]
Zed treats that file as JSONC, but not Biome. You'll have to configure Biome to treat that file as a JSONC: https://biomejs.dev/reference/configuration/#jsonparserallowcomments

**Comment by luckydye** [comment]
Actually this should be fixed, what Zed version is this?

**Comment by chungweileong94** [comment]
> Actually this should be fixed, what Zed version is this?

Yeah, not sure which versions, maybe 1.443.0+, Zed will tell Biome to treat the file as JSONC, even with `"formatter": "language_server"`.

https://github.com/user-attachments/assets/8bdb6967-da2e-482a-b5e8-5b5d639334e8

**Comment by luckydye** [comment]
I'll close it as fixed for now. If you still see this, check if the file language is set to "JSONC" in the bottom right of zed.
