### ISSUE TITLE
Version 0.1.0 failed to locate biome language server

### ISSUE THREAD

**Issue by chungweileong94** [biomejs/biome-zed#33]
In version 0.1.0, the extension doesn't able to locate the biome language server, which likely due to this change https://github.com/biomejs/biome-zed/commit/be0e8868d042ff3cceae74a035fb2fc0d0eb198b.

My current workaround is to customize the lsp binary in settings
```jsonc
"lsp": {
  "biome": {
    "binary": {
      "path": "node_modules/@biomejs/biome/bin/biome",
      "arguments": ["lsp-proxy"]
    }
  }
}
```

**Comment by chungweileong94** [comment]
So I installed biome via pnpm, and based on my understanding, biome will download the binary via postinstall script, which pnpm will put them under `node_modules/.pnpm/@biomejs+biome@1.7.3/node_modules/@biomejs/cli-xxx-xxx`. Which mean we have to do more than just `node_modules/@biomejs/cli-xxx-xxx` if we want to run it without Node.

**Comment by ematipico** [comment]
pnpm creates a symbolic link though, so `node_modules/@biomejs/cli-xxx-xxx` is still valid. Just need to follow the symbolic link, correct?

**Comment by chungweileong94** [comment]
> pnpm creates a symbolic link though

Yes, but apparently pnpm don't create symlink in `node_modules/@biomejs/cli-xxx-xxx`🫤. I think pnpm won't includes any at the root of `node_modules` that is not directly consumed by the user (dependencies in package.json). Unless we configure the hoist pattern https://pnpm.io/npmrc#hoist-pattern

**Comment by luckydye** [comment]
Yeah... I guess we need to fallback to the node script.

**Comment by luckydye** [comment]
I'm trying to use oxc_resolver, but it just resolves to "/node_modules/@biomejs/cli-darwin-arm64/biome" :/ which is wrong.

**Comment by ematipico** [comment]
I believe we need to do it ourselves, I think. Check if the binary is a symbolic link and follow it

**Comment by luckydye** [comment]
So the node_modules look like this:

<img width="361" alt="image" src="https://github.com/user-attachments/assets/2e80558a-fcf6-4db9-be7e-16632b95402e">

"optionalDependencies" are not linked directly under node_modules, which means we don't really have a link to follow.. :/ 
And the dir names in .pnpm can be a mixture of dependencies.

**Comment by ematipico** [comment]
Ah, what a bummer :/

**Comment by nhedger** [comment]
For the VS Code extension, I had to resolve the cli packages in the context of the `@biomejs/biome` packages. I wonder if it's possible with oxc_resolver.

**Comment by chungweileong94** [comment]
I checked the VSCode extension, it reminds me of yarn pnp, which I think this extension doesn't work OOB, but I think that can be fixed separately.
