### ISSUE TITLE
`JSON standard does not allow comments.` squiggly lines in json files with comments

### ISSUE THREAD

**Issue by sparrowsl** [biomejs/biome-zed#37]
I get the annoying squiggly line if I open json files that has comments _(eg: tsconfig, jsconfig)_
but in VSCode there's no warning or any lines and biome just works.

In zed (image below)
![from-zed](https://github.com/user-attachments/assets/60470de7-8715-4459-bebc-22bff1cbaecb)

in VSCode (image below)
![from-vscode](https://github.com/user-attachments/assets/b6b8afdd-eefd-49cc-afef-a0e613771b31)

**Comment by luckydye** [comment]
This is a Zed issue, vscode by default detects json files with comments as jsonc, zed does not.
See https://zed.dev/docs/configuring-zed#file-types for configuration.
