### ISSUE TITLE
File-specific biome.json file

### ISSUE THREAD

**Issue by timdang** [biomejs/biome-zed#39]
I'm not sure if this is an extension or Zed issue, but we'd like the errors for a given file to only show the relevant errors of the nearest biome.json file.

We have the following file structure:
📂 biome.json
     ➡️ 📂 API biome.json (extends parent - allows import type because NestJS)
     ➡️ 📂 client biome.json (extends parent - requires import type)
     
Currently, it seems like the errors shown for a given file only show based upon the setting of the parent biome.js. I'd prefer not to open up the API and client folders in different instances of Zed if at all possible. Thanks!

**Comment by luckydye** [comment]
Having multiple configs in the same workspace is not possible as far as I know.

Would [overrides](https://biomejs.dev/reference/configuration/#overridesitemlinter) solve yur problem? Instead of multiple configs.

**Comment by timdang** [comment]
Let me try that out. I think that'd work. Thank you.

**Comment by timdang** [comment]
I still have to keep around the child level biome.json files for cli level linting, but this fixes the issue within Zed.
