### ISSUE TITLE
Extension is breaking the "Go to definition" feature from Zed

### ISSUE THREAD

**Issue by christian-gama** [biomejs/biome-zed#40]
Installing biome extension makes the "Go to definition" stop working. Pressing F12, g d, etc. does not. Uninstalling the extension makes it work again.

**Comment by luckydye** [comment]
To me, it seems like this is a Zed issue, I got it working again by moving the ts-server langauge server in front of the biome language server like so:
```json
"language_servers": [
    "vtsls",
    "biome",
    "..."
 ],
```

**Comment by ematipico** [comment]
It's a Zed issue, Biome doesn't have this feature (yet)
