### ISSUE TITLE
biome extention is not starting

### ISSUE THREAD

**Issue by hesham-ayad** [biomejs/biome-zed#41]
I installed the extension and when I opened a project with Biome installed  in it. It wouldn't start. 
Note I installed Biome via pnpm by the way.
Biome starts just fine with lsp-config on neovim.

biome-zed-extension 0.1.1
zed 0.148.1
ubuntu 24

**Comment by ematipico** [comment]
Can you share your settings?

**Comment by hesham-ayad** [comment]
I am new to Zed, so I'm still lost
```json
{
  "features": {
    "inline_completion_provider": "none"
  },
  "ui_font_size": 14,
  "buffer_font_size": 14,
  "theme": {
    "mode": "system",
    "light": "One Light",
    "dark": "Atelier Cave Dark"
  },
  "languages": {
    "JavaScript": {
      "language_servers": ["biome", "!typescript-language-server", "..."]
    }
  }
}
```

**Comment by ematipico** [comment]
Please get accustomed to that. Our readme provides the instructions to enable Biome: https://github.com/biomejs/biome-zed?tab=readme-ov-file#configuration

**Comment by hesham-ayad** [comment]
Just got neovim working and thought Zed would be a breeze, but neovim has a much bigger community and that helped me understand what I needed to do.  Could you share a simple settings config that gets Biome running, I followed the read me instructions and thought I didn't need to add anything if I had a biome.json in the project's root directory.

In neovim I have json, css, jsx, and javascript formatting and linting handled by biome, and auto-completion is handled by tsserver. I think I should just stick to neovim till I have time to do detective work for Zed, I just thought it would be easier to configure it. Ahhhh why did I have to like Biome's linting so much.

Sorry for taking up your time.
