### ISSUE TITLE
Extension broken in Zed `0.151.1`

### ISSUE THREAD

**Issue by shellheim** [biomejs/biome-zed#44]
My `settings.json` for biome 

```jsonc
 // Biome
  "lsp": {
    "biome": {
      "settings": {
        "config_path": "~/Code/biome.json",
        "require_config_file": false
      }
    }
  },
  "formatter": {
    "language_server": {
      "name": "biome"
    }
  }
```

This extension used to work two versions before this, so maybe it's a zed thing? After installing the extension, it simply doesn't start. It works fine in neovim but nothing happens in zed buffers.

**Comment by luckydye** [comment]
Im actually not having any problems, but I see some werid behaviour too.
Like sometimes I get a "Error: biome binary not found", but the Server starts anyways. But it appears very inconsistently.

**Comment by shellheim** [comment]
Thanks for the reply. I decided to completely reinstall zed to see it's a quirk of zed and gets fixed. Here are the steps: 

1. Install zed
2. Press `Ctrl + Shift + X` to go to the extensions tab and search for `biome`, click install.
3. Press `Ctrl + ,` to edit `settings.json` and add this : 

```jsonc
 // biome
  "lsp": {
    "biome": {
      "settings": {
        "require_config_file": false
      }
    }
  },
  "formatter": {
    "language_server": {
      "name": "biome"
    }
  },
  "code_actions_on_format": {
    "source.fixAll.biome": true,
    "source.organizeImports.biome": true
  }
```
I am not using a `biome.json` because previously it would work on every js file without needing that in the root of the project, though I have it deep in my `nvim` config.

Now,

4. Open a `.js` file with a known problem, like using `forEach` instead of a `for...of` loop. 
Now you should observe that `biome` doesn't start. 

Same file using `biome` in : 
| Nvim                                                                                          | Zed                                                                                          |
| --------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------- |
| ![nvim_lint](https://github.com/user-attachments/assets/8a8a1893-9b7c-435f-9843-5da79bf328c1) | ![zed_lint](https://github.com/user-attachments/assets/af24639b-a421-421f-93b9-a1ed25d4c3eb) |

**Comment by lcdss** [comment]
For me Biome extension is showing the linter errors but nothing I do can make it to fix those errors automatically. Running manually `editor:format` doesn't work either and it only fix the errors when I click on the flash icon at a line that has an error and select `fix all auto-fixable issues` or other specific rule action. I'm using the same settings as @shellheim.

**Comment by luckydye** [comment]
> For me Biome extension is showing the linter errors but nothing I do can make it to fix those errors automatically. Running manually `editor:format` doesn't work either and it only fix the errors when I click on the flash icon at a line that has an error and select `fix all auto-fixable issues` or other specific rule action. I'm using the same settings as @shellheim.

The format command is not supposed to fix your lint errors. Linting and formatting are not seen as the same thing from biome. Tho I agree the "code_actions_on_format" stopped working some time ago. Which is likely a Zed issue.

**Comment by lcdss** [comment]
Just by updating the dependencies of this extension made it all work for me.  One think I noticed is that after a lint fix (`useSortedClasses`) the text cursor moves to the start of the next line, which is a little strange and different from what happens on vscode, where the cursor keeps at the same position.

**Comment by Aleksion** [comment]
I'm getting the biome warnings and errors, but formatting doesn't seem to work?

**Comment by luckydye** [comment]
> I'm getting the biome warnings and errors, but formatting doesn't seem to work?

Open a new issue please, if you think something is wrong. :) Check https://github.com/biomejs/biome-zed?tab=readme-ov-file#configuration before though.
