### ISSUE TITLE
Goto definition functionality breaks with biome extension installed

### ISSUE THREAD

**Issue by jon3b** [biomejs/biome-zed#51]
Mentioned [here](https://github.com/zed-industries/zed/issues/15917#issuecomment-2293625509) and still happening to me on Zed 0.156.1

**Comment by ematipico** [comment]
Biome **doesn't** support goto functionality. If the IDE breaks, it's an issue there

**Comment by jon3b** [comment]
If the extension breaks IDE functionality, then it's an issue with the extension no?

**Comment by luckydye** [comment]
@jon3b Zed has the concept of a primary Language Server, if for some reason the primary Language Server cant run Go To Definition, it wont do anything. So far my suspicion... so I would say Zed needs to handle it better.

Also I'm assuming, that you are using the "language_servers" configuration option, which is connected to all sorts of buggy behaviour at the moment.

**Comment by jodaka** [comment]
> Also I'm assuming, that you are using the "language_servers" configuration option, which is connected to all sorts of buggy behaviour at the moment.

Does that means there's a better way that doesn't break goto functionality? If so then can you point me to example/documentation?
