### ISSUE TITLE
not resolve path correctly

### ISSUE THREAD

**Issue by foxgem** [biomejs/biome-zed#56]
zed biome extension can't resolve the path correctly, see below:

<img width="436" alt="image" src="https://github.com/user-attachments/assets/64b04a93-9f0b-4b59-be2b-9c8510c2e525">

there is a config in `tsconfig.json`

```json
    "compilerOptions": {
      "paths": {
        "@/*":["./src/*"]
      },
      "baseUrl": "."
    }
```

vscode zed extension can resolve it correctly, no error.

**Comment by ematipico** [comment]
I'm not sure I understand the issue. What does Biome have to do with paths resolution? Can you provide more information _related to Biome_?

**Comment by foxgem** [comment]
I did a quick checking, this issue was gone after I restarted zed. I guess that is because of some kind of cache. currently, it works fine.

thanks for this great tools and quick response! let me close this issue.
