### ISSUE TITLE
Add "Show documentation for <rule>" to code actions

### ISSUE THREAD

**Issue by silvenon** [biomejs/biome-zed#58]
Many times when I run into a Biome error I run the CLI as well just to get the links to the rules as well. I think it would be really handy to add an additional code action for rule documentation, like ESLint has, so that I don't have to run the CLI or search Biome's docs.

I often like to read more about rules, why they're discouraged patterns, what are some alternatives etc.

![Screenshot 2024-10-22 at 22 59 40](https://github.com/user-attachments/assets/328b6f29-15a6-4288-b1e6-8caf98dc2c66)

ESLint example:

![Screenshot 2024-10-22 at 23 03 50](https://github.com/user-attachments/assets/8e825ba8-d629-4eed-8f65-fafa61d90944)

**Comment by luckydye** [comment]
This is not something we can do in this extension, you should suggest it in biome itself though: https://github.com/biomejs/biome/issues

**Comment by marjorg** [comment]
@luckydye Does this also apply to showing the rule name? Would be very handy to have when Googling/adding ignore comments.

In Zed:
![Image](https://github.com/user-attachments/assets/50a7d68e-d630-4cd2-a27f-a61ef16cc8ba)

In VSCode:
![Image](https://github.com/user-attachments/assets/47706852-b445-4696-995a-2751bd7cdfa9)

**Comment by ematipico** [comment]
@marjorg 

No, that must be done at Zed side. Biome LSP already sends the proper information, but Zed, the client, doesn't use them - as opposed to VSCode.
