### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by coolemur** [biomejs/biome-zed#61]
Zed version: Zed 0.134.4 & Zed Preview 0.162.1
Biome-zed plugin: v0.1.3

According to https://zed.dev/docs/configuring-zed#formatter this should work, but it **doesn't work**:

```
  "languages": {
    "Svelte": {
        "formatter": {
          "code_actions": {
            "source.fixAll.biome": true,
            "source.organizeImports.biome": true
          }
        }
      }
    }
```

This also **doesn't work**:

```
  "languages": {
    "Svelte": {
        "code_actions_on_format": {
          "source.fixAll.biome": true,
          "source.organizeImports.biome": true
        }
      }
    }
```

Adding these settings to root for all languages also **doesn't work**:

```
  "formatter": {
    "language_server": {
      "name": "biome"
    }
  },
  "code_actions_on_format": {
    "source.fixAll.biome": true,
    "source.organizeImports.biome": true
  },
```

While running external command **works**:

```
  "languages": {
    "Svelte": {
        "formatter": {
          "external": {
            "command": "./node_modules/@biomejs/biome/bin/biome",
            "arguments": [
              "check",
              "--write",
              "--stdin-file-path",
              "{buffer_path}"
            ]
          }
        }
      }
    }
```

Am I doing something wrong or this Plugin is currently broken?

**Comment by ematipico** [comment]
I wouldn't exclude that zed is at fault here.

I also tried it yesterday but I couldn't get it to work, however the linting works, and code actions too. So it's about formatting specifically.

**Comment by chanpod** [comment]
For what it's worth

` "formatter": {
    "language_server": {
      "name": "biome"
    }
  },`
    
Worked for me but only after I restarted zed.
