### ISSUE TITLE
Use biome binary from project PATH

### ISSUE THREAD

**Issue by abustany** [biomejs/biome-zed#62]
Would it be possible to use the biome binary from the project path, similar for example to [how the rust-analyzer Zed support works](https://zed.dev/docs/languages/rust#binary)? The version used when editing matches eg. the version in CI.

**Comment by ematipico** [comment]
We don't document it because it's mostly for development, and that's why it's in the contribution section, but it's already possible:  https://github.com/biomejs/biome-zed/blob/main/CONTRIBUTING.md#custom-biome-binary
